name: Build Release Packages
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: Create and Publish Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Dist Packages
        run: make dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
      - name: Upload Linux 64-bit Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/artifacts/GuideMe.Linux.64-bit.zip
          asset_name: GuideMe-${{ steps.get_version.outputs.VERSION }}-Linux.64-bit.zip
          asset_content_type: application/zip
      - name: Upload Windows Slim Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/artifacts/GuideMe.Windows.Slim.zip
          asset_name: GuideMe-${{ steps.get_version.outputs.VERSION }}-Windows.Slim.zip
          asset_content_type: application/zip
      - name: Upload Windows 32-bit Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/artifacts/GuideMe.Windows.32-bit.zip
          asset_name: GuideMe-${{ steps.get_version.outputs.VERSION }}-Windows.32-bit.zip
          asset_content_type: application/zip
      - name: Upload Windows 64-bit Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/artifacts/GuideMe.Windows.64-bit.zip
          asset_name: GuideMe-${{ steps.get_version.outputs.VERSION }}-Windows.64-bit.zip
          asset_content_type: application/zip